# Generated by Django 4.2.6 on 2023-11-21 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("release_date", models.DateTimeField(null=True)),
                ("projeto_url", models.URLField(null=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="review", name="date", field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="projeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projetos.post"
            ),
        ),
        migrations.DeleteModel(name="Projeto",),
    ]
