# Generated by Django 4.2.6 on 2023-11-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0002_post_review_date_alter_review_projeto_delete_projeto"),
    ]

    operations = [
        migrations.DeleteModel(name="Review",),
    ]
