# Generated by Django 4.2.6 on 2023-11-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(name="comment", options={"ordering": ["-date"]},),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("projetos", models.ManyToManyField(to="projetos.post")),
            ],
        ),
    ]
