# Generated by Django 4.2.6 on 2023-11-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0005_alter_comment_options_alter_comment_date_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="release_date", field=models.DateField(null=True),
        ),
    ]
